---
kind: pipeline
name: default

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build --pull --tag ldericher/dtools:latest .

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock