#!/bin/sh

die() {
	>&2 echo "${@}"
	exit 1
}

while getopts 'hf' opt; do
	case "${opt}" in
		h) echo "Usage: readlog [-h] [-f] <daemonname>"; exit 0;;
		f) follow=1;;
		*) die "Invalid option";;
	esac
done

shift $(( OPTIND - 1 ))

if [ ${#} -lt 1 ]; then
	die "No daemon specified!"
fi

daemonname="${1}"
logdir="/service/${daemonname}/log/main"

if [ ! -d "$logdir" ]; then
	die "Logs for '${daemonname}' not found."
fi

if [ "${follow}" -eq 1 ]; then
	tail -f "${logdir}/current" | tai64nlocal
else
	cat "${logdir}/"* | tai64nlocal | less -R +G
fi

exit 0
